# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from sanvalentin_app.views import *

admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^djangojs/', include('djangojs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^$', 'sanvalentin_app.views.iniciar_sesion', name='login'),
                       url(r'^home/$', 'sanvalentin_app.views.home', name='home'),
                       url(r'^cerrar/$', 'sanvalentin_app.views.cerrar'),
                       url(r'^descargar/backup/$', 'sanvalentin_app.views.descargar_backup', name='descargar_backup'),
                       url(r'^alumno/(?P<curso>[0-9]+)/nuevo$', 'sanvalentin_app.views.nuevo_alumno',
                           name='nuevo-alumno'),
                       url(r'^profesor/nuevo$', 'sanvalentin_app.views.nuevo_profesor', name='nuevo-profesor'),
                       url(r'^curso/nuevo/$', 'sanvalentin_app.views.nuevo_curso', name='nuevo-curso'),
                       url(r'^profesores/$', ProfesorListView.as_view(), name='listar-profesores'),
                       url(r'^direccion/$', DireccionListView.as_view(), name='direccion'),
                       url(r'^cursos/$', CursoListView.as_view(), name='listar-cursos'),
                       url(r'^cursos/(?P<pk>[0-9]+)/alumnos/$', CursoDetailView.as_view(), name='listar-cursoalumno'),
                       url(r'^cursos/(?P<pk>[0-9]+)/detalle/$', CursoDetalleDetailView.as_view(), name='detalle-curso'),
                       url(r'^cursos/(?P<pk>[0-9]+)/materias/$', CursoMateriaDetailView.as_view(),
                           name='listar-materiascurso'),
                       url(r'^profesores/detalle/(?P<pk>[0-9]+)/$', ProfesorDetailView.as_view(),
                           name='profesor-detalle'),
                       url(r'^materias/(?P<pk>[0-9]+)/$', ProfesorMateriasDetailView.as_view(), name='listar-materias'),
                       url(r'^alumnos/informe/(?P<alumno>[0-9]+)/$', IDPListView.as_view(), name='informe-alumno'),
                       url(r'^materia/evaluacion/nueva/(?P<materia>[0-9]+)/$', 'sanvalentin_app.views.nueva_evaluacion',
                           name='nueva-evaluacion'),
                       url(r'^materias/alumnos/(?P<materia>[0-9]+)/$', 'sanvalentin_app.views.alumnosMateriaNota',
                           name='materias-nota'),
                       url(r'^materia/evaluacion/descripcion/(?P<pk>[0-9]+)/$', EvaluacionDetailView.as_view(),
                           name='evaluacion'),
                       url(r'^modificar/nota/(?P<nota>[0-9]+)/$', 'sanvalentin_app.views.mod_notas', name='mod-nota'),
                       url(r'^alumnos/notas/(?P<alumno>[0-9]+)/$', AlumnoListView.as_view(), name='notas-alumno'),
                       url(r'^materias/agregar/(?P<curso>[0-9]+)/$', 'sanvalentin_app.views.agregar_materia',
                           name='nueva-materia'),
                       url(r'^alumnos/informe/(?P<pk>[0-9]+)/update/$', InformeUpdate.as_view(), name='informe-update'),
                       url(r'^asistencia/alumno/(?P<alumno>[0-9]+)/$', InformacionListView.as_view(),
                           name='asistencia-alumno'),
                       url(r'^informacion/alumno/inansistencia/(?P<info>[0-9]+)/update/$',
                           'sanvalentin_app.views.inasistenciaUpdate',
                           name='inasistencia-update'),
                       url(r'^informacion/alumno/atraso/(?P<info>[0-9]+)/update/$',
                           'sanvalentin_app.views.atrasoUpdate',
                           name='atraso-update'),
                       url(r'^nuevo-directivo/$', 'sanvalentin_app.views.agregar_directiva', name='nueva-directiva'),
                       url(r'^eliminar-directivo/(?P<pk>[0-9]+)/$', DeleteDirectivaView.as_view(), name='directiva-delete'),
                       url(r'^mod-directivo/(?P<dire>[0-9]+)/$', 'sanvalentin_app.views.directiva_update', name='directiva-update'),
                       url(r"^alumnos/(?P<pk>[0-9]+)/detalle/$", AlumnoDetailView.as_view(), name='alumno-detalle'),
                       url(r'^alumnos/matriculados/$', AlumnosMatriculadosListView.as_view(), name='alumnos-matriculados'),
                       url(r"^(?P<alumno>[0-9]+)/alumnonota.pdf$", HelloPDFView.as_view(), name='pdf'),
                       url(r"^alumnosmatriculados.pdf$", AlumnosMatriculados.as_view(), name='pdf_alumnosmatriculados'),
                       url(r'^informacion/curso/dias/(?P<dt>[0-9]+)/update/$',
                           'sanvalentin_app.views.dias_trabajados_update',
                           name='dias-update'),
                       url(r'^curso/(?P<curso>[0-9]+)/dias-trabajados/$', 'sanvalentin_app.views.dias_trabajados',
                           name='dias-trabajados'),
                       url(r'^alumno/asignar/(?P<alumno>[0-9]+)/$', 'sanvalentin_app.views.asignarcurso', name='asignar-curso'),
                       url(r'^cursos/(?P<pk>[0-9]+)/eliminar/$',DeleteCursoView.as_view(), name='curso-delete'),
                       url(r'^profesores/(?P<pk>[0-9]+)/eliminar/$',DeleteProfesorView.as_view(), name='profesor-delete'),
                       url(r'^materia/(?P<pk>[0-9]+)/eliminar/$',DeleteMateriaView.as_view(), name='materia-delete'),
                       url(r'^alumnos/(?P<pk>[0-9]+)/eliminar/$',DeleteAlumnoView.as_view(), name='alumno-delete'),
                       url(r'^alumno/detalle/(?P<pk>[0-9]+)/update/$', AlumnoUpdate.as_view(), name='alumno-update'),
                       url(r'^alumno/apoderado/(?P<pk>[0-9]+)/update/$', ApoderadoUpdate.as_view(), name='apoderado-update'),
                       url(r"^(?P<alumno>[0-9]+)/IDP.pdf$", IDPPDF.as_view(), name='pdf_IDP'),
                       url(r"^(?P<alumno>[0-9]+)/IDP1.pdf$", IDPPDF1.as_view(), name='pdf_IDP1'),
                       url(r"^(?P<alumno>[0-9]+)/IDP2.pdf$", IDPPDF2.as_view(), name='pdf_IDP2'),

                       url(r'^nueva/observacion/(?P<alumno>[0-9]+)/$', 'sanvalentin_app.views.nueva_observacion', name='nueva-observacion'),
                       url(r'^evaluacion/(?P<pk>[0-9]+)/update/$', DetalleNotaUpdate.as_view(), name='evaluacion-update'),
                       url(r'^materias/evaluacion/(?P<eva>[0-9]+)/eliminar/$','sanvalentin_app.views.deleteevaluacion', name='evaluacion-delete'),
                       url(r'^alumno/promover/(?P<alumno>[0-9]+)/$', 'sanvalentin_app.views.promoveralumno', name='promover-alumno'),
                       url(r'^matricula/(?P<pk>[0-9]+)/update/$', NMatriculaUpdate.as_view(), name='matricula-update'),
                       url(r'^cuenta/update/(?P<id_user>[0-9]+)/$', 'sanvalentin_app.views.passwordUpdate', name='cuenta-update'),
                       url(r'^materia/(?P<pk>[0-9]+)/update/$', MateriaUpdate.as_view(), name='materia-update'),
                       url(r'^curso/(?P<pk>[0-9]+)/update/$', CursoUpdate.as_view(), name='curso-update'),
                       url(r'^informe_personalidad/nuevo_item/$', 'sanvalentin_app.views.CrearInformePersonalidad', name='ip'),
                       url(r'^informe_personalidad/update/$', IPDireccionListView.as_view(), name='informe-personalidad'),
                       url(r'^informe_personalidad/update/(?P<pk>[0-9]+)/$', ItemIPUpdate.as_view(), name='update-ip'),
                       url(r'^(?P<alumno>[0-9]+)/FichaAlumnoIDP.pdf$', FichaPDF.as_view(), name='pdf_ficha'),
                       url(r'^observacion/update/(?P<pk>[0-9]+)/$', ObservacionUpdate.as_view(), name='update-obs'),
                       url(r'^alumno/antecedentesfam/(?P<pk>[0-9]+)/update/$', AnteFamUpdate.as_view(), name='antefam-update'),
                       url(r'^alumno/antecedentessoci/(?P<pk>[0-9]+)/update/$', AnteSocioUpdate.as_view(), name='antesoci-update'),
                       url(r'^alumno/salud/(?P<pk>[0-9]+)/update/$', SaludUpdate.as_view(), name='salud-update'),
                       url(r'^curso/(?P<pk>[0-9]+)/proms/$', PromediosAlumnos.as_view(), name='promedios-alumnos'),
                       url(r'^curso/(?P<curso>[0-9]+)/PromediosAlumnos.pdf$', PromediosAlumnosPDF.as_view(), name='promedios-alumnos-pdf'),

)
